### ISSUE TITLE
Game freezes when injecting mod version 4.12.0.0

### ISSUE THREAD

**Issue by REUW** [sojournercntl/NebulaInjector#1]
Injection was working fine with mod version 4.10.0.0 after auto update of the .dll the game now freezes upon injection.

**Comment by iienigma** [comment]
I'm having the same issue.

**Comment by Smp017** [comment]
oh thank god i thought i was the only one. i am also having this issue, first use when it asked for the licence key it brought the menu up, and froze. has done so ever since. using menu version 4.12 as well

**Comment by sojournercntl** [comment]
This issue is not created by NebulaInjector! Ask enough for support! 👍
